version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: suivie_courdb
    ports:
      - "3306:3306"
