name: CI/CD Suivie Academique Backend

# Le workflow se déclenche à chaque "push" sur la branche principale
on:
  push:
    branches: [ "main" ]

jobs:
  # ÉTAPE 1 : INTÉGRATION CONTINUE (CI)
  # On vérifie que le code est stable avant de faire quoi que ce soit
  test-app:
    name: Tests et Validation PHP
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Configuration de l'environnement PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, mysql

      - name: Installation des dépendances (Composer)
        run: composer install --prefer-dist --no-progress

      - name: Préparation de l'environnement de test
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Exécution des tests unitaires (PHPUnit)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:" # Test en mémoire pour plus de rapidité
        run: php artisan test

  # ÉTAPE 2 : LIVRAISON CONTINUE (CD)
  # Cette étape ne démarre que si le job "test-app" est réussi (Validé Vert)
  build-and-push:
    name: Build et Publication Docker Hub
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code source
        uses: actions/checkout@v4

      - name: Connexion sécurisée à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construction et Envoi de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # L'image est étiquetée avec "latest" pour la production
          tags: ${{ secrets.DOCKER_USERNAME }}/suivie-academique-backend:latest
